services:
    emailqueue:
        image: emailqueue-apache
        container_name: emailqueue-apache
        build:
            context: ./emailqueue
            dockerfile: ./Dockerfile
        ports:
            - "8081:80"
        networks:
            - emailqueue
        volumes:
            - ./emailqueue:/emailqueue
            - ./application.config.inc.php:/emailqueue/config/application.config.inc.php
        restart: unless-stopped

    emailqueue-mariadb:
        image: mariadb
        container_name: emailqueue-mariadb
        networks:
            - emailqueue
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql
            - ./docker/mariadb/emailqueue_init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        environment:
            - MYSQL_DATABASE=emailqueue
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped

volumes:
    emailqueue-db-data: {}

networks:
    emailqueue:
        name: emailqueue
